---
title: "Trabalho 2"
author: "Felipe Figueiredo"
date: "June 1, 2016"
output: html_document
---

```{r, echo = F}
corr  <- function (x,y) {
  n <- length(x)
  sp <- sum(x*y)
  mp <- mean(x)*mean(y)
  sdp <- sd(x)*sd(y)
  result <- (sp - n*mp)/((n - 1)*sdp)
  paste("n = ", n, "SP = ", sp, "MP = ", mp, "SDP = ", sdp, "RESULTADO = ", result)
  }

```


## 9.1 15 ####

```{r, echo = F}
x <- c(16, 25, 39, 45, 49, 64, 70, 29, 57, 22)
y <- c(109, 122, 143, 132, 199, 185, 199, 130, 175, 118)
corr(x,y)
cor(x,y)

```

## 9.1 17 ####
```{r, echo = F}
x <- c(0,1,2,4,4,5,5,5,6,6,7,7,8)
y <- c(40,41,51,48,64,69,73,75,68,93,84,90,95)
corr(x,y)
cor(x,y)

```

## 9.1 18 ####
```{r, echo = F}
x <- c(0,1,2,3,3,5,5,5,6,7,7,10)
y <- c(96,85,82,74,95,68,76,84,58,65,75,50)
corr(x,y)
cor(x,y)

```

## 4.1 29 ####
```{r, echo = F}
x <- 0:5
y <- c(1491,425,168,48,29,14)
sum(x*y)/sum(x)

```

## 4.1 35 ####
```{r, echo = F}
x <- 0:8
y <- c(0.02, 0.02,0.06,0.06,0.08,0.22,0.30,0.16,0.08)
sum(x*y)/sum(x)

```

## 4.2 15 ####
```{r, echo = F}
n <- 5
p <- 0.2
n*p

```

## 5.1 43 ####
```{r, echo = F}
m <- 93.01
s <- 0.005
x <- c(93.014, 93.018, 93.004, 92.994)
(x-m)/s

```

## 5.1 44 ####
```{r, echo = F}
m <- 335
s <- 3.5
x <- c(328, 338, 330, 341)
(x-m)/s

```

## 5.2 5 ####
```{r, echo = F}
m <- 86
s <- 5
x <- c(70,80)
(x-m)/s

```

## 5.2 13 ####
```{r, echo = F}
m <- 69.6
s <- 3
x <- c(66,72)
(x-m)/s

```

## 5.2 17 ####
```{r, echo = F}
m <- 7
s <- 1
x <- c(5,5.5,9.5,10)
(x-m)/s

```

## 5.2 23 ####
```{r, echo = F}
m <- 186
s <- 35.8
x <- c(200, 240)
(x-m)/s

```
